# %u = User Name
# 0 = Default Windows Download 
# 1 = Project Download
# Example: C:\Users\%u\Desktop\
downloadDir: 1

# Language used
# Usable languages: de, en, es, fr, it
# de: German, Deutsch
# en: English
# es: Spanish, Español
# fr: French, Français
# it: Italian, Italiano
language: en

# DO NOT CHANGE
gui: 0

# SAME
illegalChars: ['\\', '/', ':', '*', '?', '<', '>', '|', '.', ',', "'", '"', '%', '$', '~']